emitter:
    generateOnSurface: false
    name: "sparks"
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionAngle: 0.000000
    type: "point"
    shortEffect: false
    emissionRange: 100.000000
    shockwaveMode: "shockDisabeld"
    emissionVectorInverted: true
    size: [0.000000, 0.000000, 0.000000]
layer0:
    life: 0.200000
    stripeLifetime: 0.000000
    endTime: 0.100000
    scaleVelocityBase: 0.100000
    stripeVertexSpawnStep: 1.000000
    stripeStartSize: 0.000000
    type: "layer"
    stripeUScrollSpeed: 0.000000
    enableFlow: false
    stripeVScrollSpeed: 0.000000
    colorOverLife: [255.000000, 90.000000, 25.000000, 255.000000]
    stripeFadeDistanceFromTop: 0.000000
    name: "sparks"
    layerType: "particles"
    degradeStrategy: 0
    particleOrientation: 1
    inheritPosition: false
    isLong: true
    randomSpinDirection: false
    pivotPoint: [0.000000, 0.000000]
    effectFormat: 1
    useFresToAlpha: false
    fresToAlphaBias: 0.000000
    autoFPS: false
    fresToAlphaPower: 0.000000
    alphaRemapLoopCount: 1.000000
    force0: [0.000000, 0.000000, -30.000000]
    size: [0.010000, 0.010000]
    sprite: "../../../../../../Data/Gfx/Particles/alpha/Iskr"
    alphaOverLife: [0.000000, 1.000000, 0.990000, 0.000000]
    enableAlphaRemap: false
    blending: 2
    deltaTime: 0.000000
    enableFlowAnimation: false
    enableNoise: false
    useNoiseScroll: false
    useThreePointGradient: false
    stripeInheritPositionForBase: false
    enableFog: false
    enableFrameBlend: false
    loopEndTime: 4.000000
    scaleVelocityFactor: 0.600000
    startTime: 0.000000
    gradientMiddlePoint: 0.500000
    lifeVariation: 0.200000
    applyGlobalForces: false
    loopVariation: 0.000000
    loopSpriteAnimation: true
    number: 600.000000
    sizeVariation: [0.020000, 0.015000]
    velocity: 1.000000
    frameOverLifeEnabled: false
    velocityVariation: 28.000000
    velocityOverLife: [0.000000, 1.000000, 0.093000, 0.560100, 0.996500, 0.507600]
    frameOverLifeFPS: 0.000000
    randomFrameOnStart: false
    isLooped: false
    deltaVariation: 0.000000
    usePerspectiveMapping: false
    activeLODS: [1, 1, 0, 0]
    forceCount: 1
    forceOverLife0: [0.000000, 1.000000, 1.000000, 0.000000]
