emitter:
    emissionAngle: 60.000000
    emissionRange: 80.000000
    emissionVector: [0.000000, -1.000000, 0.000000]
    emissionVectorInverted: true
    name: "smoke"
    radius: 2.000000
    shortEffect: false
    size: [6.000000, 0.000000, 0.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.198900, 0.990000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    colorOverLife: [113.828796, 115.478600, 120.416344, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dstBlendFactor: "BLEND_ONE_MINUS_SRC_ALPHA"
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.200000
    frameOverLifeEnabled: true
    frameOverLifeFPS: 16.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 2.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smoke1"
    number: 600.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.000000
    size: [20.000000, 20.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 0.108800, [2.515300, 2.515300], 1.000000, [6.000000, 6.000000]]
    spin: 30.000000
    spinVariation: 30.000000
    sprite: "../../../../../../../Data/Gfx/Particles/UI/fog"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.020000
    type: "layer"
    velocity: 100.000000
    velocityOverLife: [0.000000, 1.000000, 0.157900, 0.211700, 0.996500, 0.000000]
    velocityVariation: 100.000000
