emitter:
    emissionAngle: 0.000000
    emissionRange: 1.000000
    emissionVector: [0.000000, 0.000000, 0.010000]
    emissionVectorInverted: true
    name: "glow_tank_japan1"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.450000, 0.150000, 0.990000, 0.000000]
    blending: 3
    colorOverLife: [255.000000, 109.272369, 24.902723, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.100000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 0.800000
    lifeVariation: 0.800000
    loopEndTime: 1000.000000
    loopSpriteAnimation: true
    loopVariation: 0.020000
    name: "glow"
    number: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: true
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [200.000000, 200.000000]
    sprite: "../../../../../../../Data/Gfx/Particles/UI/o2_expGlowB"
    startTime: 0.000000
    type: "layer"
