emitter:
    emissionAngle: 0.000000
    emissionRange: 0.000000
    emissionVector: [0.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "heaven_glow1"
    shortEffect: true
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaRemapLoopCount: 0.000000
    blending: 1
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    dragForceTimingType0: "const"
    effectFormat: 1
    enableAlphaRemap: true
    enableFog: true
    enableFrameBlend: false
    endTime: 0.500000
    frameOverLifeEnabled: true
    frameOverLifeFPS: 85.000000
    fresToAlphaBias: 0.000000
    fresToAlphaPower: 0.000000
    gradientMiddlePoint: 0.500000
    inheritPosition: true
    isLong: false
    isLooped: false
    killParticles0: false
    layerType: "single"
    life: 0.500000
    loopEndTime: 0.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "ribbon"
    number: 1.000000
    particleOrientation: 1
    pivotPoint: [-0.650000, 0.900000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [280.000000, 28.000000]
    sprite: "../../../../../../../Data/Gfx/Particles/UI/Login3.0/ribbon_anim"
    startTime: 0.000000
    stripeInheritPositionForBase: false
    stripeLifetime: 1.000000
    stripeStartSize: 0.000000
    stripeUScrollSpeed: 0.000000
    stripeVScrollSpeed: 0.000000
    stripeVertexSpawnStep: 1.000000
    type: "layer"
    useFresToAlpha: false
    useNoiseScroll: false
    usePerspectiveMapping: true
    useThreePointGradient: false
    startTime0: 0.000000
    endTime0: 15.000000
