emitter:
    emissionAngle: 0.000000
    emissionRange: 0.000000
    emissionVector: [0.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    generateOnSurface: true
    name: "fire_smoke"
    shortEffect: true
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaRemapLoopCount: 0.000000
    blending: 1
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableAlphaRemap: true
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 85.000000
    fresToAlphaBias: 0.000000
    fresToAlphaPower: 0.000000
    gradientMiddlePoint: 0.500000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "single"
    life: 1000.100000
    loopEndTime: 0.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "ribbon"
    number: 1.000000
    particleOrientation: 1
    pivotPoint: [-0.650000, 0.900000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [60.000000, 60.000000]
    sprite: "../../../../../../../Data/Gfx/Particles/UI/Login3.0/sauron_3"
    startTime: 0.000000
    stripeInheritPositionForBase: false
    stripeLifetime: 0.000000
    stripeStartSize: 0.000000
    stripeUScrollSpeed: 0.000000
    stripeVScrollSpeed: 0.000000
    stripeVertexSpawnStep: 1.000000
    type: "layer"
    useFresToAlpha: false
    useNoiseScroll: false
    usePerspectiveMapping: true
    useThreePointGradient: false
