emitter:
    emissionRange: 0.000000
    emissionVector: [0.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "flow"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 1]
    blinding: 3
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "single"
    life: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "flow"
    number: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [200.000000, 200.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 0.300000, [0.300000, 0.300000], 0.990000, [0.300000, 0.300000]]
    sprite: "../../../../../../../Data/Gfx/Particles/UI/Login3.0/zasvet"
    spin: 100.000000
    startTime: 0.000000
    type: "layer"
    velocity: 3.000000
