emitter:
    emissionAngle: 0.000000
    emissionRange: 10.000000
    emissionVector: [-1.000000, 0.000000, 0.000000]
    emissionVectorInverted: true
    name: "smoke"
    shortEffect: false
    size: [0.000000, 100.000000, 600.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.325714, 0.346838, 0.735238, 0.352498, 0.990000, 0.000000]
    angle: 1.000000
    angleVariation: 360.000000
    blending: 1
    colorOverLife: [162.000000, 158.000000, 123.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 14.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "smoke3"
    number: 3.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [300.000000, 300.000000]
    spin: 5.000000
    spinVariation: 10.000000
    sprite: "../../../../Gfx/Particles/UI/Login3.0/Fx_DustSpray_two"
    startTime: 0.000000
    type: "layer"
    velocity: 20.000000
    velocityVariation: 20.000000
