emitter:
    emissionAngle: 0.000000
    emissionRange: 60.000000
    emissionVector: [-0.200000, -1.000000, 0.000000]
    emissionVectorInverted: true
    name: "fire_smoke1"
    shortEffect: false
    size: [130.000000, 0.000000, 20.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.365714, 0.137758, 0.681905, 0.097333, 1.000000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 3
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: true
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 20.000000
    inheritPosition: true
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 0.700000
    loopEndTime: 100.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "fire2"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.003000
    size: [50.000000, 50.000000]
    sizeVariation: [20.000000, 20.000000]
    spin: 30.000000
    spinVariation: 30.000000
    sprite: "../../../../Gfx/Particles/UI/Login3.0/Fire_1"
    startTime: 0.000000
    type: "layer"
    velocity: 15.000000
    velocityVariation: 15.000000
layer1:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.140000, 1.000000, 0.480176, 1.000000, 0.753304, 1.000000, 1.000000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 3
    colorOverLife: [0.000000, [242.015564, 159.311279, 70.902718, 255.000000], 0.994643, [242.015564, 53.571983, 24.579765, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: true
    endTime: 1000.000000
    frameOverLifeEnabled: true
    frameOverLifeFPS: 30.000000
    inheritPosition: true
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 0.600000
    loopEndTime: 100.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "fire2"
    number: 20.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.000000
    size: [60.000000, 60.000000]
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [2.000000, 2.000000]]
    sizeVariation: [20.000000, 20.000000]
    spin: 30.000000
    spinVariation: 30.000000
    sprite: "../../../../Gfx/Particles/UI/Login3.0/smoke"
    startTime: 0.000000
    type: "layer"
    velocity: 30.000000
    velocityVariation: 15.000000
