emitter:
    emissionAngle: 0.000000
    emissionRange: 30.000000
    emissionVector: [-1.000000, -0.200000, 0.000000]
    emissionVectorInverted: true
    name: "sparks"
    shortEffect: false
    size: [0.000000, 100.000000, 20.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.152381, 0.597006, 0.470476, 0.574692, 1.000000, 0.000000]
    blending: 3
    colorRandom: [255.000000, 0.996109, 0.996109, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    force0: [0.000000, 50.000000, 0.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: true
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 2.800000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "sparks"
    number: 5.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: true
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.004000
    size: [3.000000, 3.000000]
    sizeVariation: [2.000000, 3.000000]
    spin: 150.000000
    spinVariation: 150.000000
    sprite: "../../../../Gfx/Particles/UI/Login3.0/treil"
    startTime: 0.000000
    type: "layer"
    velocity: 400.000000
    velocityVariation: 300.000000
