emitter:
    emissionAngle: 0.000000
    emissionRange: 100.000000
    emissionVector: [-1.000000, -1.000000, 0.000000]
    emissionVectorInverted: true
    name: "sparks"
    shortEffect: false
    size: [0.000000, 600.000000, 0.000000]
    type: "rect"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 1.000000, 0.603524, 1.000000, 0.990000, 0.000000]
    blending: 3
    colorOverLife: [255.000000, 58.968872, 9.961089, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 1000.000000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 3.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "sparks"
    number: 2.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.020000
    size: [6.000000, 2.000000]
    sizeVariation: [3.000000, 5.000000]
    sprite: "../../../../Gfx/Particles/UI/Login3.0/treil"
    startTime: 0.000000
    type: "layer"
    velocity: 200.000000
    velocityVariation: 60.000000
