emitter:
    size: [0.000000, 0.000000, 0.000000]
    name: "debris"
    type: "point"
    emissionVectorInverted: true
    shortEffect: false
    emissionAngle: 0.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionRange: 60.000000
layer0:
    activeLODS: [1, 1, 0, 0]
    stripeVScrollSpeed: 0.000000
    stripeLifetime: 0.000000
    deltaTime: 0.000000
    startTime: 0.000000
    stripeVertexSpawnStep: 1.000000
    layerType: "particles"
    lifeVariation: 1.000000
    isLong: false
    stripeStartSize: 0.000000
    number: 70.000000
    stripeFadeDistanceFromTop: 0.000000
    loopSpriteAnimation: true
    stripeUScrollSpeed: 0.000000
    enableFog: true
    name: "debris1"
    type: "layer"
    degradeStrategy: 0
    pivotPoint: [-0.000000, -0.000000]
    useFresToAlpha: false
    fresToAlphaBias: 0.000000
    fresToAlphaPower: 0.000000
    alphaRemapLoopCount: 1.000000
    sprite: "../../../../../../Data/Gfx/Particles/alpha/ground"
    enableAlphaRemap: false
    blending: 1
    enableFlow: false
    loopVariation: 0.000000
    angle: 90.000000
    enableFrameBlend: false
    enableFlowAnimation: false
    stripeInheritPositionForBase: false
    frameOverLifeEnabled: false
    enableNoise: false
    useNoiseScroll: false
    scaleVelocityBase: 0.000000
    forceCount: 1
    scaleVelocityFactor: 0.100000
    life: 1.000000
    spinVariation: 90.000000
    size: [0.025000, 0.025000]
    sizeVariation: [0.025000, 0.025000]
    usePerspectiveMapping: false
    velocityVariation: 8.000000
    sizeOverLifeXY: [1.500000, 1.500000]
    velocity: 2.000000
    forceOverLife0: [0.000000, 0.600000, 0.990000, 0.000000]
    velocityOverLife: [0.000000, 1.000000, 0.093000, 0.560100, 0.996500, 0.507600]
    spin: 400.000000
    randomSpinDirection: true
    angleVariation: 90.000000
    colorOverLife: [118.000000, 98.000000, 44.000000, 255.000000]
    frameOverLifeFPS: 0.000000
    randomFrameOnStart: true
    endTime: 0.100000
    isLooped: false
    deltaVariation: 0.000000
    loopEndTime: 4.000000
    inheritPosition: false
    particleOrientation: 1
    effectFormat: 1
    force0: [0.000000, 0.000000, -28.000000]
layer1:
    activeLODS: [1, 1, 0, 0]
    stripeVScrollSpeed: 0.000000
    stripeLifetime: 0.000000
    deltaTime: 0.000000
    startTime: 0.000000
    stripeVertexSpawnStep: 1.000000
    layerType: "particles"
    lifeVariation: 1.000000
    isLong: false
    stripeStartSize: 0.000000
    number: 70.000000
    stripeFadeDistanceFromTop: 0.000000
    loopSpriteAnimation: true
    stripeUScrollSpeed: 0.000000
    enableFog: true
    name: "debris2"
    type: "layer"
    degradeStrategy: 0
    pivotPoint: [-0.000000, -0.000000]
    useFresToAlpha: false
    fresToAlphaBias: 0.000000
    fresToAlphaPower: 0.000000
    alphaRemapLoopCount: 1.000000
    sprite: "../../../../../../Data/Gfx/Particles/alpha/ground_one"
    enableAlphaRemap: false
    blending: 1
    enableFlow: false
    loopVariation: 0.000000
    angle: 90.000000
    enableFrameBlend: false
    enableFlowAnimation: false
    stripeInheritPositionForBase: false
    frameOverLifeEnabled: false
    enableNoise: false
    useNoiseScroll: false
    scaleVelocityBase: 0.000000
    forceCount: 1
    scaleVelocityFactor: 0.100000
    life: 1.000000
    spinVariation: 90.000000
    size: [0.025000, 0.025000]
    sizeVariation: [0.025000, 0.025000]
    usePerspectiveMapping: false
    velocityVariation: 8.000000
    sizeOverLifeXY: [1.500000, 1.500000]
    velocity: 2.000000
    forceOverLife0: [0.000000, 0.600000, 0.990000, 0.000000]
    velocityOverLife: [0.000000, 1.000000, 0.093000, 0.560100, 0.996500, 0.507600]
    spin: 400.000000
    randomSpinDirection: false
    angleVariation: 90.000000
    colorOverLife: [118.000000, 98.000000, 44.000000, 255.000000]
    frameOverLifeFPS: 0.000000
    randomFrameOnStart: true
    endTime: 0.100000
    isLooped: false
    deltaVariation: 0.000000
    loopEndTime: 4.000000
    inheritPosition: false
    particleOrientation: 6
    effectFormat: 1
    force0: [0.000000, 0.000000, -28.000000]
layer2:
    activeLODS: [1, 1, 0, 0]
    stripeVScrollSpeed: 0.000000
    stripeLifetime: 0.000000
    deltaTime: 0.000000
    startTime: 0.000000
    stripeVertexSpawnStep: 1.000000
    layerType: "particles"
    lifeVariation: 1.000000
    isLong: false
    stripeStartSize: 0.000000
    number: 70.000000
    stripeFadeDistanceFromTop: 0.000000
    loopSpriteAnimation: true
    stripeUScrollSpeed: 0.000000
    enableFog: true
    name: "debris3"
    type: "layer"
    degradeStrategy: 0
    pivotPoint: [-0.000000, -0.000000]
    useFresToAlpha: false
    fresToAlphaBias: 0.000000
    fresToAlphaPower: 0.000000
    alphaRemapLoopCount: 1.000000
    sprite: "../../../../../../Data/Gfx/Particles/alpha/ground"
    enableAlphaRemap: false
    blending: 1
    enableFlow: false
    loopVariation: 0.000000
    angle: 90.000000
    enableFrameBlend: false
    enableFlowAnimation: false
    stripeInheritPositionForBase: false
    frameOverLifeEnabled: false
    enableNoise: false
    useNoiseScroll: false
    scaleVelocityBase: 0.000000
    forceCount: 1
    scaleVelocityFactor: 0.100000
    life: 1.000000
    spinVariation: 90.000000
    size: [0.050000, 0.050000]
    sizeVariation: [0.025000, 0.025000]
    usePerspectiveMapping: false
    velocityVariation: 8.000000
    sizeOverLifeXY: [1.500000, 1.500000]
    velocity: 2.000000
    forceOverLife0: [0.000000, 0.600000, 0.990000, 0.000000]
    velocityOverLife: [0.000000, 1.000000, 0.093000, 0.560100, 0.996500, 0.507600]
    spin: 400.000000
    randomSpinDirection: false
    angleVariation: 90.000000
    colorOverLife: [118.000000, 98.000000, 44.000000, 255.000000]
    frameOverLifeFPS: 0.000000
    randomFrameOnStart: true
    endTime: 0.100000
    isLooped: false
    deltaVariation: 0.000000
    loopEndTime: 4.000000
    inheritPosition: false
    particleOrientation: 6
    effectFormat: 1
    force0: [0.000000, 0.000000, -28.000000]
layer3:
    activeLODS: [1, 1, 0, 0]
    stripeVScrollSpeed: 0.000000
    stripeLifetime: 0.000000
    deltaTime: 0.000000
    startTime: 0.000000
    stripeVertexSpawnStep: 1.000000
    layerType: "particles"
    lifeVariation: 1.000000
    isLong: false
    stripeStartSize: 0.000000
    number: 70.000000
    stripeFadeDistanceFromTop: 0.000000
    loopSpriteAnimation: true
    stripeUScrollSpeed: 0.000000
    enableFog: true
    name: "debris4"
    type: "layer"
    degradeStrategy: 0
    pivotPoint: [-0.000000, -0.000000]
    useFresToAlpha: false
    fresToAlphaBias: 0.000000
    fresToAlphaPower: 0.000000
    alphaRemapLoopCount: 1.000000
    sprite: "../../../../../../Data/Gfx/Particles/alpha/rock"
    enableAlphaRemap: false
    blending: 1
    enableFlow: false
    loopVariation: 0.000000
    angle: 90.000000
    enableFrameBlend: false
    enableFlowAnimation: false
    stripeInheritPositionForBase: false
    frameOverLifeEnabled: false
    enableNoise: false
    useNoiseScroll: false
    scaleVelocityBase: 0.000000
    forceCount: 1
    scaleVelocityFactor: 0.100000
    life: 1.000000
    spinVariation: 90.000000
    size: [0.050000, 0.050000]
    sizeVariation: [0.035000, 0.035000]
    usePerspectiveMapping: false
    velocityVariation: 8.000000
    sizeOverLifeXY: [1.500000, 1.500000]
    velocity: 2.000000
    forceOverLife0: [0.000000, 0.600000, 0.990000, 0.000000]
    velocityOverLife: [0.000000, 1.000000, 0.093000, 0.560100, 0.996500, 0.507600]
    spin: 400.000000
    randomSpinDirection: true
    angleVariation: 90.000000
    colorOverLife: [118.000000, 98.000000, 44.000000, 255.000000]
    frameOverLifeFPS: 0.000000
    randomFrameOnStart: true
    endTime: 0.100000
    isLooped: false
    deltaVariation: 0.000000
    loopEndTime: 4.000000
    inheritPosition: false
    particleOrientation: 1
    effectFormat: 1
    force0: [0.000000, 0.000000, -28.000000]
