emitter:
    generateOnSurface: false
    name: "dust"
    emissionVector: [1.000000, 0.000000, 0.000000]
    emissionAngle: 0.000000
    type: "oncircle"
    shortEffect: false
    emissionRange: 360.000000
    shockwaveMode: "shockDisabeld"
    emissionVectorInverted: true
    radius: 0.500000
    size: [0.000000, 0.000000, 0.000000]
layer0:
    life: 5.000000
    stripeLifetime: 0.000000
    endTime: 0.100000
    scaleVelocityBase: 1.000000
    stripeVertexSpawnStep: 1.000000
    stripeStartSize: 0.000000
    type: "layer"
    stripeUScrollSpeed: 0.000000
    enableFlow: false
    stripeVScrollSpeed: 0.000000
    colorOverLife: [89.000000, 97.000000, 111.000000, 255.000000]
    stripeFadeDistanceFromTop: 0.000000
    name: "dust"
    layerType: "particles"
    degradeStrategy: 2
    particleOrientation: 1
    inheritPosition: false
    isLong: false
    randomSpinDirection: true
    pivotPoint: [0.000000, 0.000000]
    effectFormat: 1
    useFresToAlpha: false
    fresToAlphaBias: 0.000000
    autoFPS: false
    fresToAlphaPower: 0.000000
    alphaRemapLoopCount: 1.000000
    force0: [0.100000, 0.100000, -0.100000]
    size: [0.750000, 0.750000]
    sprite: "../../../../../../Data/Gfx/Particles/alpha/explosion_smoke_white"
    alphaOverLife: [0.000000, 1.000000, 0.990000, 0.000000]
    enableAlphaRemap: false
    blending: 1
    deltaTime: 0.000000
    enableFlowAnimation: false
    enableNoise: false
    useNoiseScroll: false
    useThreePointGradient: false
    stripeInheritPositionForBase: false
    enableFog: true
    enableFrameBlend: false
    loopEndTime: 5.000000
    scaleVelocityFactor: 0.000000
    startTime: 0.000000
    gradientMiddlePoint: 0.500000
    applyGlobalForces: false
    loopVariation: 0.000000
    loopSpriteAnimation: true
    number: 400.000000
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [3.000000, 3.000000]]
    velocity: 0.300000
    frameOverLifeFPS: 0.000000
    spin: 20.000000
    spinVariation: 10.000000
    frameOverLifeEnabled: false
    randomFrameOnStart: false
    isLooped: false
    deltaVariation: 0.000000
    usePerspectiveMapping: false
    activeLODS: [0, 1, 0, 0]
    forceCount: 1
    forceOverLife0: [0.000000, 0.000000, 1.000000, 1.000000]
