emitter:
    generateOnSurface: false
    name: "sparks"
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionAngle: 0.000000
    type: "oncircle"
    shortEffect: false
    emissionRange: 160.000000
    shockwaveMode: "shockDisabeld"
    emissionVectorInverted: true
    radius: 0.500000
    size: [0.000000, 0.000000, 0.000000]
layer0:
    life: 0.500000
    stripeLifetime: 0.000000
    endTime: 0.100000
    scaleVelocityBase: 0.000000
    stripeVertexSpawnStep: 1.000000
    stripeStartSize: 0.000000
    type: "layer"
    stripeUScrollSpeed: 0.000000
    enableFlow: false
    stripeVScrollSpeed: 0.000000
    stripeFadeDistanceFromTop: 0.000000
    name: "sparks"
    layerType: "particles"
    degradeStrategy: 0
    particleOrientation: 1
    inheritPosition: false
    isLong: true
    randomSpinDirection: false
    pivotPoint: [0.000000, 0.000000]
    effectFormat: 1
    useFresToAlpha: false
    fresToAlphaBias: 0.000000
    autoFPS: false
    fresToAlphaPower: 0.000000
    alphaRemapLoopCount: 1.000000
    force0: [0.000000, 0.000000, -50.000000]
    size: [0.010000, 0.010000]
    sprite: "../../../../../../Data/Gfx/Particles/alpha/Iskr_one"
    alphaOverLife: 0.700000
    enableAlphaRemap: false
    blending: 2
    deltaTime: 0.000000
    enableFlowAnimation: false
    enableNoise: false
    useNoiseScroll: false
    useThreePointGradient: false
    stripeInheritPositionForBase: false
    enableFog: true
    enableFrameBlend: false
    loopEndTime: 6.000000
    scaleVelocityFactor: 0.600000
    startTime: 0.000000
    gradientMiddlePoint: 0.500000
    lifeVariation: 0.500000
    applyGlobalForces: false
    loopVariation: 0.000000
    loopSpriteAnimation: true
    number: 500.000000
    sizeVariation: [0.010000, 0.010000]
    velocity: 1.000000
    frameOverLifeEnabled: false
    velocityVariation: 20.000000
    velocityOverLife: [0.000000, 1.000000, 0.093000, 0.560100, 0.996500, 0.507600]
    colorRandom: [0.000000, [255.000000, 156.000000, 17.000000, 255.000000], 0.152100, [255.000000, 255.000000, 255.000000, 255.000000], 0.352100, [255.000000, 103.000000, 1.000000, 255.000000], 0.525600, [255.000000, 255.000000, 255.000000, 255.000000], 0.695900, [255.000000, 142.000000, 97.000000, 255.000000], 0.866100, [255.000000, 255.000000, 255.000000, 255.000000]]
    frameOverLifeFPS: 0.000000
    randomFrameOnStart: false
    isLooped: false
    deltaVariation: 0.000000
    usePerspectiveMapping: false
    activeLODS: [1, 1, 0, 0]
    forceCount: 1
