emitter:
    emissionAngle: 0.000000
    emissionRange: 10.000000
    emissionVector: [0.000000, -1.000000, 1.000000]
    emissionVectorInverted: true
    name: "sparks1"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 0, 0]
    alphaOverLife: [0.000000, 0.807200, 1.000000, 0.400000]
    blending: 3
    colorRandom: [0.000000, [255.000000, 167.000000, 44.000000, 255.000000], 0.995200, [255.000000, 233.000000, 202.000000, 255.000000]]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -50.000000]
    forceCount: 1
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: true
    isLooped: false
    layerType: "particles"
    life: 1.000000
    lifeVariation: 1.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "sparks1_1"
    number: 300.000000
    particleOrientation: 8
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 1.000000
    size: [0.020000, 0.020000]
    sprite: "../../../../../Data/Gfx/Particles/alpha/o2_expGlowB"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 0.093000, 0.560100, 0.996500, 0.507600]
    velocityVariation: 28.000000
