emitter:
    emissionRange: 0.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    generateOnSurface: false
    innerRadius: 0.500000
    name: "smoke"
    radius: 4.000000
    shockwaveMode: "shockDisabeld"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "sphere"
layer0:
    activeLODS: [1, 1, 1, 1]
    alphaOverLife: [0.000000, 0.000000, 0.070000, 0.400000, 0.557596, 0.291971, 0.960000, 0.000000]
    alphaRemapLoopCount: 1.000000
    angle: 25.000000
    angleVariation: 355.000000
    applyGlobalForces: false
    autoFPS: false
    backwardTurbulenceProbability0: 0
    backwardTurbulenceProbability1: 0
    blending: 1
    colorOverLife: [149.000000, 149.000000, 156.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    depthDifferenceSlope: 2.000000
    dragForceBoxSize0: [1.000000, 1.000000, 1.000000]
    dragForceBoxSize1: [1.000000, 1.000000, 1.000000]
    dragForceCount: 2
    dragForceInfinityRange0: true
    dragForceInfinityRange1: true
    dragForceLine1: [0.000000, [-2.000000, 0.000000, 0.000000], 1.000000, [1.000000, 0.000000, 0.000000]]
    dragForcePosition0: [0.000000, 0.000000, 0.000000]
    dragForcePosition1: [0.000000, 0.000000, 0.000000]
    dragForcePower0: [0.500000, 0.500000, 0.700000]
    dragForcePower1: [-2.000000, 0.000000, 0.000000]
    dragForceRadius0: 1.000000
    dragForceRadius1: 1.000000
    dragForceRotation0: [0.000000, 0.000000, 0.000000]
    dragForceRotation1: [0.000000, 0.000000, 0.000000]
    dragForceShape0: "box"
    dragForceShape1: "box"
    dragForceTimingType0: "const"
    dragForceTimingType1: "ovr_prt"
    effectFormat: 1
    enableAlphaRemap: false
    enableFlow: false
    enableFlowAnimation: false
    enableFog: true
    enableFrameBlend: true
    enableNoise: false
    endTime: 0.200000
    endTime0: 15.000000
    endTime1: 15.000000
    forceDirection0: [0.000000, 0.000000, 1.000000]
    forceDirection1: [0.000000, 0.000000, 1.000000]
    forceIsActive0: true
    forceIsActive1: true
    forceName0: "Drag"
    forceName1: "Gravity"
    forceType0: "drag"
    forceType1: "grav"
    forceWindBias0: 1.000000
    forceWindBias1: 1.000000
    forceWindFreq0: 0.000000
    forceWindFreq1: 0.000000
    forceWindTurb0: 0.000000
    forceWindTurb1: 0.000000
    frameOverLifeEnabled: true
    frameOverLifeFPS: 12.000000
    fresToAlphaBias: 0.000000
    fresToAlphaPower: 0.000000
    gradientMiddlePoint: 0.500000
    inheritPosition: false
    isGlobal0: false
    isGlobal1: false
    isLong: false
    isLooped: false
    killParticles0: false
    killParticles1: false
    layerType: "particles"
    life: 2.500000
    lifeVariation: 1.000000
    loopEndTime: 100.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "smoke"
    normalAsReflectionVector0: true
    normalAsReflectionVector1: true
    number: 250.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    planeScale0: 5.000000
    planeScale1: 5.000000
    pointGravityRadius0: 1.000000
    pointGravityRadius1: 1.000000
    pointGravityUseRandomPointsOnSphere0: false
    pointGravityUseRandomPointsOnSphere1: false
    randomFrameOnStart: false
    randomSpinDirection: true
    randomizeReflectionForce0: false
    randomizeReflectionForce1: false
    reflectionChaos0: 0.000000
    reflectionChaos1: 0.000000
    reflectionPercent0: 100
    reflectionPercent1: 100
    rndReflectionForceMax0: 1.100000
    rndReflectionForceMax1: 1.100000
    rndReflectionForceMin0: 1.000000
    rndReflectionForceMin1: 1.000000
    scaleVelocityBase: 1.000000
    scaleVelocityFactor: 0.100000
    size: [8.000000, 8.000000]
    sizeOverLifeXY: [0.000000, [0.000000, 0.000000], 0.213689, [0.832117, 0.832117], 0.930000, [1.000000, 1.000000]]
    sizeVariation: [3.000000, 3.000000]
    softParticles: false
    spin: 4.000000
    spinOverLife: [0.000000, 6.000000, 1.000000, 0.000000]
    spinVariation: 2.000000
    spritePath: "~res:/Gfx/Particles/alpha/fog"
    startTime: 0.100000
    startTime0: 0.000000
    startTime1: 0.000000
    stripeFadeDistanceFromTop: 0.000000
    stripeLifetime: 20.000000
    stripeStartSize: 1.000000
    stripeUScrollSpeed: 0.000000
    stripeVScrollSpeed: -0.010000
    stripeVertexSpawnStep: 1.000000
    type: "layer"
    useFresToAlpha: false
    useNoiseScroll: false
    usePerspectiveMapping: false
    useThreePointGradient: false
    velocity: 2.000000
    velocityOverLife: [0.000000, 10.000000, 0.083987, 1.576642, 1.000000, 0.000000]
    velocityThreshold0: 0.300000
    velocityThreshold1: 0.300000
    velocityVariation: 1.000000
    windTurbulenceFrequency0: 0.000000
    windTurbulenceFrequency1: 0.000000
    worldAlign0: true
    worldAlign1: true
