emitter:
    emissionAngle: 90.0000
    emissionRange: 90.0000
    emissionVector: [-0.0000, -0.0000, 1.0000]
    emissionVectorInverted: "true"
    name: "fire"
    radius: 0.2000
    shortEffect: "false"
    size: [0.0000, 1.0000, 0.0000]
    type: "oncircle"

layer0:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.0000, 0.0000, 0.1228, 0.2832, 0.7386, 0.2640, 0.9965, 0.0000]
    angle: 60.0000
    angleVariation: 60.0000
    colorOverLife: [0.0000, [248.7121, 152.5097, 44.6303, 255.0000], 0.9959, [135.8443, 17.5798, 0.0000, 255.0000]]
    degradeStrategy: 2
    deltaTime: 0.0000
    deltaVariation: 0.0000
    dstBlendFactor: "BLEND_ONE"
    effectFormat: 1
    enableFog: "true"
    enableFrameBlend: "false"
    endTime: 2.5000
    force0: [0.5000, 0.0500, 0.1000]
    force1: [0.0000, [0.0000, 0.0000, 10.0474], 11.7647, [0.0000, 0.0000, 10.0474], 34.9673, [0.0000, 0.0000, 5.2007], 99.5098, [0.0000, 0.0000, 1.7262]]
    forceCount: 2
    forceOverLife0: [0.0000, 1.0000, 75.6721, 2.1470]
    forceOverLife1: [0.0000, 0.0700, 0.4820, 0.0945, 1.0000, 0.5152]
    frameOverLifeEnabled: "false"
    frameOverLifeFPS: 20.0000
    inheritPosition: "false"
    isLong: "false"
    isLooped: "false"
    layerType: "particles"
    life: 0.4185
    lifeVariation: 0.4180
    loopEndTime: 5.0000
    loopSpriteAnimation: "true"
    loopVariation: 0.0000
    name: "fire"
    number: 24.0000
    numberVariation: 2.0000
    particleOrientation: 1
    pivotPoint: [0.0000, 0.0000]
    randomFrameOnStart: "false"
    randomSpinDirection: "false"
    scaleVelocityBase: 1.0000
    scaleVelocityFactor: 0.0000
    size: [0.4000, 0.4000]
    sizeOverLifeXY: [0.0000, [1.0000, 1.0000], 0.9900, [2.0000, 2.0000]]
    spinVariation: 60.0000
    sprite: "../../../../../Data/Gfx/Particles/fog"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.0000
    type: "layer"
    velocity: 1.0000

layer1:
    activeLODS: [0, 1, 0, 0]
    alphaOverLife: [0.0000, 0.0000, 0.1123, 0.0000, 0.1965, 0.8619, 0.7035, 0.8047, 0.9965, 0.0000]
    angle: 60.0000
    angleVariation: 60.0000
    colorOverLife: [186.0000, 190.0000, 198.0000, 255.0000]
    degradeStrategy: 2
    deltaTime: 0.0000
    deltaVariation: 0.0000
    dstBlendFactor: "BLEND_ONE_MINUS_SRC_ALPHA"
    effectFormat: 1
    enableFog: "true"
    enableFrameBlend: "false"
    endTime: 2.5000
    force0: [0.5000, 0.0500, 0.1000]
    force1: [0.0000, [0.0000, 0.0000, 10.0474], 11.7647, [0.0000, 0.0000, 10.0474], 34.9673, [0.0000, 0.0000, 5.2007], 99.5098, [0.0000, 0.0000, 1.7262]]
    forceCount: 2
    forceOverLife0: [0.0000, 1.0000, 75.6721, 2.1470]
    forceOverLife1: [0.0000, 0.0700, 0.4820, 0.0945, 1.0000, 0.5152]
    frameOverLifeEnabled: "false"
    frameOverLifeFPS: 20.0000
    inheritPosition: "false"
    isLong: "false"
    isLooped: "false"
    layerType: "particles"
    life: 1.0000
    lifeVariation: 0.4180
    loopEndTime: 5.0000
    loopSpriteAnimation: "true"
    loopVariation: 0.0000
    name: "smoke"
    number: 24.0000
    numberVariation: 2.0000
    particleOrientation: 1
    pivotPoint: [0.0000, 0.0000]
    randomFrameOnStart: "false"
    randomSpinDirection: "false"
    scaleVelocityBase: 0.0000
    scaleVelocityFactor: 0.0000
    size: [0.4000, 0.4000]
    sizeOverLifeXY: [0.0000, [1.0000, 1.0000], 1.0000, [3.0000, 3.0000]]
    spinVariation: 60.0000
    sprite: "../../../../../Data/Gfx/Particles/fog"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.0000
    type: "layer"
    velocity: 1.0000
    velocityOverLife: [0.0000, 1.0000, 1.0000, 0.1207]

