emitter:
    emissionAngle: 0.000000
    emissionRange: 60.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionVectorInverted: true
    name: "debris2"
    shortEffect: false
    size: [0.000000, 0.000000, 0.000000]
    type: "shockwave"
layer0:
    activeLODS: [1, 1, 0, 0]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [197.000000, 194.000000, 188.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -18.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 1.000000, 0.990000, 0.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 1.000000
    lifeVariation: 1.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "debris2_1"
    number: 200.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: true
    randomSpinDirection: true
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.100000
    size: [0.025000, 0.025000]
    sizeOverLifeXY: [1.500000, 1.500000]
    sizeVariation: [0.025000, 0.025000]
    spin: 400.000000
    spinVariation: 90.000000
    sprite: "../../../../../Data/Gfx/Particles/alpha/white_debris_anim"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 0.093000, 0.560100, 0.996500, 0.507600]
    velocityVariation: 15.000000
layer1:
    activeLODS: [1, 1, 0, 0]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [158.000000, 155.000000, 151.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -18.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 1.000000, 0.990000, 0.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 1.000000
    lifeVariation: 1.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "debris2_2"
    number: 200.000000
    particleOrientation: 6
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: true
    randomSpinDirection: false
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.100000
    size: [0.025000, 0.025000]
    sizeOverLifeXY: [1.500000, 1.500000]
    sizeVariation: [0.025000, 0.025000]
    spin: 400.000000
    spinVariation: 90.000000
    sprite: "../../../../../Data/Gfx/Particles/alpha/white_debris_anim_one"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 0.093000, 0.560100, 0.996500, 0.507600]
    velocityVariation: 15.000000
layer2:
    activeLODS: [1, 1, 0, 0]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [127.000000, 125.000000, 121.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -18.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 1.000000, 0.990000, 0.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 1.000000
    lifeVariation: 1.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "debris2_3"
    number: 100.000000
    particleOrientation: 6
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: true
    randomSpinDirection: false
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.100000
    size: [0.050000, 0.050000]
    sizeOverLifeXY: [1.500000, 1.500000]
    sizeVariation: [0.025000, 0.025000]
    spin: 400.000000
    spinVariation: 90.000000
    sprite: "../../../../../Data/Gfx/Particles/alpha/white_debris_anim_two"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 0.093000, 0.560100, 0.996500, 0.507600]
    velocityVariation: 15.000000
layer3:
    activeLODS: [1, 1, 0, 0]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 1
    colorOverLife: [220.000000, 217.000000, 210.000000, 255.000000]
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: true
    enableFrameBlend: false
    endTime: 0.100000
    force0: [0.000000, 0.000000, -18.000000]
    forceCount: 1
    forceOverLife0: [0.000000, 1.000000, 0.990000, 0.000000]
    frameOverLifeEnabled: false
    frameOverLifeFPS: 0.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 1.000000
    lifeVariation: 1.000000
    loopEndTime: 4.000000
    loopSpriteAnimation: true
    loopVariation: 0.000000
    name: "debris2_4"
    number: 100.000000
    particleOrientation: 1
    pivotPoint: [-0.000000, -0.000000]
    randomFrameOnStart: true
    randomSpinDirection: true
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.100000
    size: [0.050000, 0.050000]
    sizeOverLifeXY: [1.500000, 1.500000]
    sizeVariation: [0.035000, 0.035000]
    spin: 400.000000
    spinVariation: 90.000000
    sprite: "../../../../../Data/Gfx/Particles/alpha/white_debris_anim_one"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityOverLife: [0.000000, 1.000000, 0.093000, 0.560100, 0.996500, 0.507600]
    velocityVariation: 15.000000
