emitter:
    3d: "true"
    emissionAngle: 0.0000
    emissionRange: 0.0000
    emissionVector: [0.0000, 0.0000, 1.0000]
    emissionVectorInverted: "true"
    life: 10.0000
    radius: 1.0000
    shortEffect: "false"
    size: [0.0000, 0.0000, 0.0000]
    type: "shockwave"

layer0:
    activeLODS: [1, 1, 1, 1]
    alignToMotion: 0.0000
    alphaOverLife: [0.0000, 0.0000, 0.3101, 0.2736, 0.4729, 0.1885, 0.7907, 0.0388, 0.9900, 0.0000]
    angle: 90.0000
    angleVariation: 90.0000
    colorOverLife: [235.0000, 253.0000, 255.0000, 255.0000]
    deltaTime: 0.0000
    deltaVariation: 0.0000
    dstBlendFactor: "BLEND_ONE_MINUS_SRC_ALPHA"
    enableFog: "true"
    enableFrameBlend: "false"
    endTime: 0.1000
    force0: [0.0000, 0.0000, 0.1000]
    forceCount: 1
    forceOverLife0: [0.0000, 1.0000, 0.9900, 0.0000]
    frameOverLifeEnabled: "false"
    frameOverLifeFPS: 6.0000
    inheritPosition: "true"
    isDisabled: "false"
    isLooped: "false"
    layerType: "particles"
    life: 4.0000
    lifeVariation: 1.0000
    loopEndTime: 4.0000
    loopSpriteAnimation: "false"
    loopVariation: 0.0000
    name: "water3"
    number: 200.0000
    particleOrientation: 8
    pivotPoint: [0.0000, 0.0000]
    randomFrameOnStart: "false"
    randomSpinDirection: "true"
    scaleVelocityBase: 0.0000
    scaleVelocityFactor: 0.0000
    sizeOverLifeXY: [0.0000, [1.0000, 1.0000], 1.0000, [4.0000, 4.0000]]
    spin: 5.0000
    spinVariation: 5.0000
    sprite: "../../../../../Data/Gfx/Particles/water"
    srcBlendFactor: "BLEND_SRC_ALPHA"
    startTime: 0.0000
    type: "layer"
    velocityOverLife: [0.0000, 1.0000, 0.0200, 0.0400, 0.3000, 0.0000]
    size:
        externalVariable: "velocity"
        modification_line: [0.0000, [0.5000, 0.5000], 1.0000, [1.0000, 1.0000]]
        value_line: [6.0000, 6.0000]
    velocity:
        externalVariable: "velocity"
        modification_line: [0.0000, 0.5000, 0.9940, 1.0000]
        value_line: 10.0000

