emitter:
    emissionAngle: 118.713600
    emissionRange: 0.000000
    emissionVector: [-0.000000, -0.000000, 1.000000]
    emissionVectorInverted: true
    name: "exp"
    shortEffect: true
    size: [0.000000, 0.000000, 0.000000]
    type: "point"
layer0:
    activeLODS: [1, 1, 1, 0]
    animSpeedOverLife: [0.000000, 0.500000, 0.182500, 0.503600, 0.328100, 0.985400]
    blending: 2
    degradeStrategy: 0
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: true
    endTime: 0.060000
    frameOverLifeEnabled: true
    frameOverLifeFPS: 30.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 0.500000
    loopEndTime: 5.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "exp"
    number: 52.691700
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.000000
    size: [0.500000, 0.500000]
    sizeOverLifeXY: [0.000000, [3.000000, 3.000000], 1.000000, [6.000000, 6.000000]]
    sprite: "../../../../../Data/Gfx/Particles/additive/hit_anim"
    startTime: 0.000000
    type: "layer"
    velocity: 2.000000
layer1:
    activeLODS: [1, 1, 1, 0]
    alphaOverLife: [0.018900, 1.000000, 1.000000, 0.000000]
    angle: 90.000000
    angleVariation: 90.000000
    blending: 3
    colorOverLife: [255.000000, 147.000000, 38.000000, 255.000000]
    degradeStrategy: 2
    deltaTime: 0.000000
    deltaVariation: 0.000000
    effectFormat: 1
    enableFog: false
    enableFrameBlend: false
    endTime: 0.060000
    frameOverLifeEnabled: false
    frameOverLifeFPS: 60.000000
    inheritPosition: false
    isLong: false
    isLooped: false
    layerType: "particles"
    life: 0.200000
    loopEndTime: 5.000000
    loopSpriteAnimation: false
    loopVariation: 0.000000
    name: "exp2"
    number: 200.000000
    particleOrientation: 1
    pivotPoint: [0.000000, 0.000000]
    randomFrameOnStart: false
    randomSpinDirection: false
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 1.000000
    size: [0.500000, 0.500000]
    sizeOverLifeXY: [0.000000, [0.100000, 0.100000], 1.000000, [4.000000, 4.000000]]
    sprite: "../../../../../Data/Gfx/Particles/alpha/pul"
    startTime: 0.000000
    type: "layer"
    velocity: 1.000000
    velocityVariation: 1.000000
