emitter:
    size: [0.000000, 0.000000, 0.000000]
    name: "smoke"
    type: "point"
    emissionVectorInverted: true
    shortEffect: false
    emissionAngle: 0.000000
    emissionVector: [0.000000, 0.000000, 1.000000]
    emissionRange: 30.000000
layer0:
    activeLODS: [0, 1, 0, 0]
    stripeVScrollSpeed: 0.000000
    stripeLifetime: 0.000000
    deltaTime: 0.000000
    startTime: 0.000000
    stripeVertexSpawnStep: 1.000000
    layerType: "particles"
    lifeVariation: 0.500000
    isLong: false
    stripeStartSize: 0.000000
    number: 400.000000
    stripeFadeDistanceFromTop: 0.000000
    loopSpriteAnimation: false
    stripeUScrollSpeed: 0.000000
    enableFog: true
    name: "smoke"
    type: "layer"
    degradeStrategy: 2
    pivotPoint: [0.000000, 0.000000]
    useFresToAlpha: false
    fresToAlphaBias: 0.000000
    fresToAlphaPower: 0.000000
    alphaRemapLoopCount: 1.000000
    sprite: "../../../../../../Data/Gfx/Particles/alpha/fog"
    enableAlphaRemap: false
    blending: 1
    enableFlow: false
    loopVariation: 0.000000
    angle: 90.000000
    enableFrameBlend: false
    enableFlowAnimation: false
    stripeInheritPositionForBase: false
    frameOverLifeEnabled: true
    enableNoise: false
    useNoiseScroll: false
    scaleVelocityBase: 0.000000
    forceCount: 1
    scaleVelocityFactor: 0.000000
    life: 3.000000
    spinVariation: 10.000000
    size: [0.750000, 0.750000]
    usePerspectiveMapping: false
    velocityVariation: 15.000000
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [4.000000, 4.000000]]
    velocity: 3.000000
    velocityOverLife: [0.000000, 1.000000, 0.050900, 0.065700, 0.990000, 0.000000]
    spin: 10.000000
    randomSpinDirection: true
    angleVariation: 90.000000
    alphaOverLife: [0.005300, 0.418000, 0.645600, 0.195500, 0.990000, 0.000000]
    colorOverLife: [113.000000, 113.000000, 118.000000, 255.000000]
    frameOverLifeFPS: 100.000000
    randomFrameOnStart: false
    endTime: 0.060000
    isLooped: false
    deltaVariation: 0.000000
    loopEndTime: 4.000000
    inheritPosition: false
    particleOrientation: 1
    effectFormat: 1
    force0: [0.000000, 0.000000, -10.000000]
