emitter:
    size: [0.000000, 0.000000, 0.000000]
    name: "exp"
    type: "point"
    emissionVectorInverted: true
    shortEffect: true
    emissionAngle: 118.713600
    emissionVector: [-0.000000, -0.000000, 1.000000]
    emissionRange: 0.000000
layer0:
    activeLODS: [1, 1, 1, 0]
    stripeVScrollSpeed: 0.000000
    stripeLifetime: 0.000000
    deltaTime: 0.000000
    startTime: 0.000000
    stripeVertexSpawnStep: 1.000000
    layerType: "particles"
    isLong: false
    stripeStartSize: 0.000000
    number: 52.691700
    stripeFadeDistanceFromTop: 0.000000
    loopSpriteAnimation: false
    stripeUScrollSpeed: 0.000000
    enableFog: false
    name: "exp"
    type: "layer"
    degradeStrategy: 0
    pivotPoint: [0.000000, 0.000000]
    useFresToAlpha: false
    fresToAlphaBias: 0.000000
    fresToAlphaPower: 0.000000
    alphaRemapLoopCount: 1.000000
    sprite: "../../../../../../Data/Gfx/Particles/additive/exp_anim_fire"
    enableAlphaRemap: false
    blending: 2
    enableFlow: false
    loopVariation: 0.000000
    enableFrameBlend: true
    enableFlowAnimation: false
    stripeInheritPositionForBase: false
    frameOverLifeEnabled: true
    enableNoise: false
    useNoiseScroll: false
    scaleVelocityBase: 0.000000
    scaleVelocityFactor: 0.000000
    life: 0.500000
    size: [0.300000, 0.300000]
    usePerspectiveMapping: false
    sizeOverLifeXY: [0.000000, [1.000000, 1.000000], 1.000000, [8.000000, 8.000000]]
    velocity: 2.000000
    animSpeedOverLife: [0.000000, 0.500000, 0.182500, 0.503600, 0.328100, 0.985400]
    randomSpinDirection: false
    frameOverLifeFPS: 30.000000
    randomFrameOnStart: false
    endTime: 0.060000
    isLooped: false
    deltaVariation: 0.000000
    loopEndTime: 5.000000
    inheritPosition: false
    particleOrientation: 1
    effectFormat: 1
